version: '3.8'

services:
  sla-monitoring-tool:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=your-secret-key-change-this-in-production
    volumes:
      # Mount for persistent data if needed
      - ./data:/usr/src/app/data
    restart: unless-stopped